import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:maybank2u/util/hook/hook.dart';
import 'package:maybank2u/util/util.dart';

class Secure2u extends HookWidget {
  const Secure2u({Key key, this.onPressCancel}) : super(key: key);

  final VoidCallback onPressCancel;

  @override
  Widget build(BuildContext context) {
    final _locale = useLocale();

    return Scaffold(
      key: const Key('secure2u screen'),
      appBar: AppBar(
        backgroundColor: Colors.yellowAccent,
        elevation: 0,
        leading: IconButton(
          key: const Key('secure2u cancel'),
          onPressed: onPressCancel,
          icon: Icon(Icons.close),
          color: Colors.black,
        ),
        actions: <Widget>[
          Container(
            width: MediaQuery.of(context).size.width * .6,
            padding:
                const EdgeInsets.symmetric(vertical: 10).copyWith(left: 20),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.start,
              children: <Widget>[
                Text(
                  _locale.autoGeneratedIn,
                  style: Theme.of(context).textTheme.title,
                ),
                _TimerText()
              ],
            ),
          )
        ],
      ),
      backgroundColor: Colors.yellowAccent,
      body: Container(),
    );
  }
}

class _TimerText extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final _timer = useTicker(Duration(minutes: 3));

    final _seconds = convertDigitToDoubleDigit(_timer.value.inSeconds % 60);

    return Text(
      '${_timer.value.inMinutes}:$_seconds',
      style: Theme.of(context).textTheme.title,
    );
  }
}
